In [3]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [4]:
#pip install numpy
#NumPy library used for numerical computations and array operations.
import numpy as np


In [7]:
np.__version__

'1.26.4'

In [9]:
marks=[56,89,78]
total= [100,100,100]
# below element by element division does not work with lists
marks/total

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [161]:
stdnt_marks=np.array([56,89,78])
stdnt_marks

array([56, 89, 78])

In [166]:
# 1 D Array
total= np.array([100,100,100])

In [127]:
stdnt_marks/total

array([0.56, 0.89, 0.78])

In [3]:
# Functions for Numpy Arrays
stdnt_marks=np.array([56,89,78])
stdnt_marks

array([56, 89, 78])

In [4]:
stdnt_marks.dtype

dtype('int32')

In [5]:
#dimention of an array
stdnt_marks.ndim

1

In [6]:
#size of each element
stdnt_marks.size

3

In [7]:
stdnt_marks.shape

(3,)

In [8]:
stdnt_marks.itemsize

4

In [19]:
# Indexing 2 dimentional data
data = np.array([[10,3],[15,2],[25,2],[30,3]],dtype='int32')
data

array([[10,  3],
       [15,  2],
       [25,  2],
       [30,  3]])

In [4]:
# 2D_array[row,cols]
data[1,]

array([15,  2])

In [5]:
data[1,:]

array([15,  2])

In [20]:
data[0:2,[0]]  #slicing the last index will be exclusive

array([[10],
       [15]])

In [140]:
data[2,1]

2

In [141]:
data.ndim

2

In [169]:
data.shape

(4, 2)

### Introduction to numpy Array:

In [196]:
ones_arr = np.ones((3,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [149]:
#ones() and zeros()
zero_arr = np.zeros((2,1))
zero_arr

array([[0.],
       [0.]])

In [6]:
#The asarray() method in NumPy can be used to create an array from data that already exists
## convert list to ndarray 
x = [1,2,3] 
a = np.asarray(x) 
print (a)

[1 2 3]


In [8]:
x = [1,2,3] 
a1 = np.array(x) 
print (a1)

[1 2 3]


In [152]:
#From existing data array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
#Copy Array using numpy.copy()
# create a numpy array
               0  1  2
a = np.array([[8, 2, 3],   0
              [4, 7, 6]])  1

# copy contents of a to b
b = a.copy()

# modify a
a[1, 2] = 13

# check if b has remained the same
print(a)
print(b)

[[ 8  2  3]
 [ 4  7 13]]
[[8 2 3]
 [4 7 6]]


In [142]:
#using numerical range arange()
arr = np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [198]:
# importing numpy module
import numpy as np

# creating list
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

# creating numpy array
sample_array = np.array([list_1,
                        list_2,
                        list_3])

print("Numpy multi dimensional array in python\n",
sample_array)


Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
# print shape of the array
print("Shape of the array :",
      sample_array.shape)

Shape of the array : (3, 4)


In [4]:
import numpy as np

sample_array1 = np.array([[0, 4, 2],
                         [3, 4, 5],
                         [23, 4, 5],
                         [2, 34, 5],
                         [5, 6, 7]])

print("shape of the array :",sample_array1.shape)
print(sample_array1)

shape of the array : (5, 3)
[[ 0  4  2]
 [ 3  4  5]
 [23  4  5]
 [ 2 34  5]
 [ 5  6  7]]


In [6]:
# Import module
import numpy as np

# Creating the array
sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

# display data type
print("Data type of the array 1 :",sample_array_1.dtype)

print("Data type of array 2 :",sample_array_2.dtype)

print(sample_array_1)
print(sample_array_2)

Data type of the array 1 : int32
Data type of array 2 : float64
[[0 4 2]]
[0.2 0.4 2.4]


In [11]:
import numpy as np
#numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.

np.arange(1, 20 , 2,dtype = np.float32)
 

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [9]:
np.arange(1, 20 , 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
#using numerical range linspace()
#numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits.


np.linspace(2, 10, 3)


array([ 2.,  6., 10.])

In [206]:
import numpy as np

np.linspace(3.5, 10, 3,dtype = np.int32)


array([ 3,  6, 10])

In [12]:
import numpy as np

np.linspace(3.5, 10, 3)

array([ 3.5 ,  6.75, 10.  ])

In [178]:
#numpy.ones(): This function is used to get a new array of given shape and type, filled with ones(1).
import numpy as np

np.ones([4, 3],dtype = np.int32)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.zeros([4, 3],
         dtype = np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
import numpy as np

# create a 2-D array 
array1 = np.array([[2, 4, 6],
                  [1, 3, 5]])

# check the dimension of array1
print(array1.ndim) 

# return total number of elements in array1
print(array1.size)

# return a tuple that gives size of array in each dimension
print(array1.shape)

# check the data type of array1
print(array1.dtype)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)

2
6
(2, 3)
int32
4


In [27]:
#Providing Two arange Arguments
arr1= np.arange(start=1, stop=10, step=2)
print(arr1)

arr2 = np.arange(start=1, stop=10)
print(arr2)

[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]


## Basic numpy operation

In [181]:
#NumPy ADD Operator
#We can also use the add operator “+” to perform addition of two arrays.
import numpy as np
a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])
print(a+b)

[ 13  24 105 206 507]


In [182]:
np.add(a, b)

array([ 13,  24, 105, 206, 507])

In [30]:
#NumPy Subtract Operator

a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])
np.subtract(a, b)

array([  7,  16,  95, 194, 493])

In [31]:
print(a-b)

[  7  16  95 194 493]


In [32]:
#NumPy Multiply function
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
np.multiply(a, b)

array([21, 12, 20, 30,  7])

In [33]:
print(a*b)

[21 12 20 30  7]


In [34]:
#NumPy Divide Function
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
np.divide(a,b)

array([2.33333333, 0.75      , 0.8       , 0.83333333, 0.14285714])

In [35]:
print(a/b)

[2.33333333 0.75       0.8        0.83333333 0.14285714]


In [184]:
#NumPy Mod Function # Modulus
#We use both the functions to output the remainder of the division of two arrays
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])
np.mod(a,b)

array([1, 3, 4, 5, 1])

In [185]:
a%b

array([1, 3, 4, 5, 1])

In [37]:
np.remainder(a,b)

array([1, 3, 4, 5, 1])

In [48]:
#Arithmetic Operators with single dimentional array
# Create two arrays using np.arange
a = np.arange(6)  # [0,1, 2, 3, 4, 5]
b = np.arange(6,12)  

# Element-wise arithmetic operations
result_addition = a + b
result_subtraction = a - b
result_multiplication = a * b
result_division = a / b
result_modulus = a % b
result_exponentiation = a ** b


print(a)
print(b)
print("Addition:", result_addition)
print("Subtraction:", result_subtraction)
print("Multiplication:", result_multiplication)
print("Division:", result_division)
print("Modulus:", result_modulus)
print("Exponentiation:", result_exponentiation)


[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
Addition: [ 6  8 10 12 14 16]
Subtraction: [-6 -6 -6 -6 -6 -6]
Multiplication: [ 0  7 16 27 40 55]
Division: [0.         0.14285714 0.25       0.33333333 0.4        0.45454545]
Modulus: [0 1 2 3 4 5]
Exponentiation: [       0        1      256    19683  1048576 48828125]


In [10]:
#Arithmetic Operators with multi dimentional array
c = np.arange(0,12).reshape(3,4)    # 3X4 = 12  # 3 X 3 = 9 
d = np.ones((3,4))


print(c)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
result_addition1 = c + d
result_subtraction1 = c - d
result_multiplication1 = c * d
result_division1 = c / d
result_modulus1 = c % d
result_exponentiation1 = c ** d

print("Addition:", result_addition1)
print("Subtraction:", result_subtraction1)
print("Multiplication:", result_multiplication1)
print("Division:", result_division1)
print("Modulus:", result_modulus1)
print("Exponentiation:", result_exponentiation1)

Addition: [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Subtraction: [[-1.  0.  1.  2.]
 [ 3.  4.  5.  6.]
 [ 7.  8.  9. 10.]]
Multiplication: [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
Division: [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
Modulus: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Exponentiation: [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [13]:
c = np.arange(0,12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
#Arithmetic Operators with multi dimentional array
c = np.arange(0,12).reshape(2,4)
c

ValueError: cannot reshape array of size 12 into shape (2,4)

In [13]:
##Matrix product
#(0*5) + (1*8) + (2*11) = 0 + 8 + 22 = 30
#(0*6) + (1*9) + (2*12) = 0 + 9 + 24 = 33

#(3*5) + (4*8) + (5*11) = 15 + 32 + 55 = 102
#(3*6) + (4*9) + (5*12) = 18 + 36 + 60 = 114

#(6*5) + (7*8) + (8*11) = 30 + 56 + 88 = 174
#(6*6) + (7*9) + (8*12) = 36 + 63 + 96 = 195


arr = np.arange(0,9).reshape(3,3)
arr1 = np.arange(5,14).reshape(3,3)
print(arr)
print(arr1)

print(np.dot(arr,arr1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[ 30  33  36]
 [102 114 126]
 [174 195 216]]


In [72]:
#Matrix product 0x1 = 0, 1x1=1 , 2x1= 2  (0+1+2)= 3
e = np.arange(0,9).reshape(3,3)
f = np.ones((3,3))


print(e)

print(f)

print(np.dot(e,f))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [12]:
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(a.ndim)

2


In [13]:
print(a)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


## Hill Cipher using matrix product

The Hill Cipher is a cryptographic algorithm that falls under the category of polygraphic substitution ciphers. Unlike simple substitution ciphers that replace individual letters with other letters, polygraphic ciphers operate on groups of letters to enhance security. The Hill Cipher uses linear algebra concepts to encrypt and decrypt messages.

Here's how the Hill Cipher works:

Key Generation: The encryption key is a matrix (usually a square matrix) containing numerical values. This matrix is chosen carefully and kept secret between the sender and receiver.

Encryption:The plaintext is divided into blocks of a fixed size (usually equal to the dimensions of the key matrix).
Each block is represented as a matrix of numerical values, where each letter corresponds to a number (A=0, B=1, ..., Z=25).
The key matrix is multiplied with each plaintext block matrix using matrix multiplication.
The result is taken modulo 26 to ensure the values remain within the alphabet's range.
The resulting numerical values are then converted back to letters to create the ciphertext.

Decryption:The encrypted message (ciphertext) is divided into blocks, just like during encryption.
The inverse of the key matrix (mod 26) is used to decrypt each block.
The decryption process involves the same steps as encryption but uses the inverse key matrix.

Plain Text: HE LLO
Cipher Key: [11 9 8 17]

Step-by-step encryption using modulo 26 and the provided approach:






Key Size: The size of the key matrix should match the size of the blocks you're using for encryption. If you're encrypting text in blocks of 2 letters, you need a 2x2 key matrix; for blocks of 3 letters, you need a 3x3 key matrix, and so on.

the key matrix's values are typically chosen from the set of integers modulo 26, because each letter in the alphabet is represented by a number modulo 26 (A=0, B=1, ..., Z=25). This ensures that the encryption and decryption operations stay within the range of the alphabet.

In [168]:
# A   B   C   D   E   F   G   H   I   J   K   L   M   N  O   P   Q   R   S   T   U   V   W   X   Y   Z
# 0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25

In [1]:
#Step 1: Import the libraries

import numpy as np

In [2]:
# Step 2: Create numpy array a as first column of plain text and array b as key
a = np.array([7, 4])  # H E
b = np.array([[11, 9], [8, 17]])  # key
print(a)
print(b)

[7 4]
[[11  9]
 [ 8 17]]


You're creating an array a to represent the first column of the plain text "ed" as numbers [4, 3]. 

In [3]:
# Step 3: Perform matrix product between array a and b
c = np.dot(a, b)
print(c)

[109 131]


In [4]:
109%26

5

Here, you're performing matrix multiplication between array a and key matrix b, resulting in the array c.

In [5]:
# Step 4: Perform encryption of plain text using mod function
h = np.mod(c,26)
print("h=",h)

h= [5 1]


You're applying the modulo 26 operation to the values in array c, which represents the intermediate result of the matrix multiplication. This ensures that the resulting numbers are within the range of the alphabet (0-25)


In [6]:
# Step 5: Create numpy array d of second column of plain text and array b as key
d = np.array([4, 11])  # E L

In [7]:
#Step 6: Perform matrix product between array d and b
f = np.dot(d, b)
print(f)

[132 223]


In [8]:
132 % 26

2

In [9]:
#Step 7: Perform encyption of plain text using mod function
h1 = np.mod(f, 26)
print("h1=", h1)

h1= [ 2 15]


This gives you the encrypted result for the second column.

In [10]:
#Step 8:Create a numpy array g of last column of plain text and array b as key
#For the third column "LL":
g = np.array([11, 11])  # L L
print(g)

[11 11]


In [11]:
#Step 9: Perform matrix product between array g and b
j = np.dot(g, b)
print(j)


[209 286]


In [12]:
#Step 10: Perform encyption of plain text using mod function
h2 = np.mod(j, 26)
print("h2", h2)

h2 [1 0]


In [13]:
#Step 11:Create a numpy array g of last column of plain text and array b as key
#For the fourth column "LO":
k = np.array([11, 14])  # L O



In [14]:
#Step 12: Perform matrix product between array g and b
m = np.dot(k, b)
print(m)

[233 337]


In [16]:
233%26

25

In [17]:
#Step 10: Perform encyption of plain text using mod function
h3 = np.mod(m, 26)
print("h3", h3)

h3 [25 25]


In [18]:
h , h1,h2, h3

(array([5, 1], dtype=int32),
 array([ 2, 15], dtype=int32),
 array([1, 0], dtype=int32),
 array([25, 25], dtype=int32))

Convert the resulting numbers [5, 1], [2, 15], [1, 0], and [25, 25] back to letters using the mapping A=0, B=1, ..., Z=25:

[5, 1] becomes "FB"

[2, 15] becomes "CP"

[1, 0] becomes "BA"

[25, 25] becomes "ZZ"

So, the encrypted message for the plain text "HELLO" using the key matrix [11 9 8 17] and the provided approach with modulo 26 operation is "FBCPBAZZ".So Plain Text in encypted format will be "FBCPBAZZ"

In [ ]:
# A   B   C   D   E   F   G   H   I   J   K   L   M   N  O   P   Q   R   S   T   U   V   W   X   Y   Z
# 0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25

In [11]:
# Write a Python program to declare a list and NumPy arrays(1-D, 2-D, and
# 3-D) and compare the size of the list and the arrays. Also, compare the
# size of each element in the list and the arrays (in terms of memory
# occupancy). 

import numpy as np
import sys

# Declare a list
my_list = [1, 2, 3, 4, 5]

# Declare NumPy arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
array_3d = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])

# Compare the size of the list and the arrays
size_list = sys.getsizeof(my_list)
size_array_1d = array_1d.nbytes
size_array_2d = array_2d.nbytes
size_array_3d = array_3d.nbytes

print("Size of the list:", size_list, "bytes")
print("Size of the 1-D array:", size_array_1d, "bytes")
print("Size of the 2-D array:", size_array_2d, "bytes")
print("Size of the 3-D array:", size_array_3d, "bytes")

# Compare the size of each element in the list and the arrays
# For the list, we will use the size of an element directly
# For NumPy arrays, we use the itemsize attribute

element_size_list = sys.getsizeof(my_list[0])
element_size_array_1d = array_1d.itemsize
element_size_array_2d = array_2d.itemsize
element_size_array_3d = array_3d.itemsize

print("Size of each element in the list:", element_size_list, "bytes")
print("Size of each element in the 1-D array:", element_size_array_1d, "bytes")
print("Size of each element in the 2-D array:", element_size_array_2d, "bytes")
print("Size of each element in the 3-D array:", element_size_array_3d, "bytes")

Size of the list: 104 bytes
Size of the 1-D array: 20 bytes
Size of the 2-D array: 40 bytes
Size of the 3-D array: 80 bytes
Size of each element in the list: 28 bytes
Size of each element in the 1-D array: 4 bytes
Size of each element in the 2-D array: 4 bytes
Size of each element in the 3-D array: 4 bytes
