In [8]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np  

In [16]:
arr = np.array([1,2,3,4,5]) # 1. using list
print(type(arr))
print(arr)
arr.dtype

<class 'numpy.ndarray'>
[1 2 3 4 5]


dtype('int32')

In [18]:
arr = np.array((1, 2, 3, 4, 5)) # 2. using a tuple
print(arr)

[1 2 3 4 5]


In [28]:
arr = np.zeros((5,5,4)) # 3. using zeros function 
print (arr)
arr.ndim

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


3

In [32]:
arr = np.ones((5,2,5)) #4. using ones function
print(arr)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [34]:
arr = np.arange(1,10,2) #5. using arange 
print (arr) 
# difference between range and arange function

[1 3 5 7 9]


In [40]:
arr = np.arange(1,2,0.1)
print (arr) 

a = range(1,2, 0.1)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


TypeError: 'float' object cannot be interpreted as an integer

In [48]:
arr= np.linspace(1,10,5).astype('int32') # 6. using linspace 
print (arr)
# difference between linespace and arange 

[ 1  3  5  7 10]


In [11]:
# copy an array
arr = np.ones((2,2))
c = np.copy(arr)
arr[0][0] = 0
print (arr)
print (c)

[[0. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2 dimensional array
#  to check the number of dimensions  

In [58]:
a = np.array(42) 
b = np.array([1, 2, 3, 4, 5.0])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [60]:
# to check the properties of the array
# 2. ndarray.shape
print(d.ndim)
print (d.shape)
print(d.size)
print(d.dtype)
print (d.itemsize)

3
(2, 2, 3)
12
int32
4


In [18]:
# to create an array of 5 dimens 
arr = np.array([1, 2, 3, 4], ndmin=5) # use ndmin
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [62]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr) 
print('shape of array :', arr.shape) # what will be the output?

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [20]:
# #reshaping an array: changing the shape of array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# convert into 3D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [76]:
#flattening the array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
newarr = arr.reshape(-1)
print(newarr)

(2, 3)
[1 2 3 4 5 6]


In [5]:
# **Using `arange`, `linspace`, and `reshape`:**
# - Create a NumPy array using `arange` that contains values from 0 to 15. Reshape this array into a 3x5 matrix. Next,
# create another NumPy array using `linspace` that contains 10 evenly spaced values between 0 and 1. Print both arrays and their shapes.

arr = np.arange(0,15)
newarr = arr.reshape(3,5)
a = np.linspace(0,1,10)
print(arr)
print(newarr)
print(a)
print(arr.shape)
print(newarr.shape)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
(15,)
(3, 5)
(10,)


In [11]:
#    **Data Transformation and Analysis:**
#    - You have a dataset containing sales figures for 12 months stored in a flat list: `[250, 300, 450, 500, 600, 650, 700, 750, 800, 850, 900, 950]`. 
#    - Use NumPy to reshape this data into a 4x3 matrix representing quarterly sales (each row is a quarter, and each column is a month).
#    - Calculate the total sales for each quarter and store them in a new NumPy array. 
#    - Print the reshaped matrix and the total sales for each quarter.

import numpy as np

sales = np.array([250, 300, 450, 500, 600, 650, 700, 750, 800, 850, 900, 950])
detail_sales = sales.reshape(4,3)
print(detail_sales)
sum = 0
count = 0
quater = 0
total_sales = np.array([0,0,0,0])
def total(detail_sales):
    global quater 
    global sum 
    global count
    global total_sales
    for i in range(0,4):
        while count < 3:
            sum = sum + detail_sales[i][count]
            print(sum)
            count+= 1

        print(f"The total sales in {i} is {sum}")
        total_sales[i] = sum
        count=0
    return 

total(detail_sales)

print(total_sales)


[[250 300 450]
 [500 600 650]
 [700 750 800]
 [850 900 950]]
250
550
1000
The total sales in 0 is 1000
1500
2100
2750
The total sales in 1 is 2750
3450
4200
5000
The total sales in 2 is 5000
5850
6750
7700
The total sales in 3 is 7700
[1000 2750 5000 7700]
